"""manifest projection tables

The typed, version-pinned projection of the Bungie manifest that
``dd.manifest_ingest`` writes and anchor reads, replacing the in-process
download-extract-parse pipeline. Create-only: every table is new, so this adds no
locks to anything already serving, and an empty projection is the pre-ingest state
every reader already degrades on.

Revision ID: b603eb4c27bc
Revises: b7df22b81517
Create Date: 2026-08-11 12:54:17.466433+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

#: ``jsonb`` on the deployed Postgres, plain ``JSON`` on the SQLite the suite runs
#: against — the same variant ``schemas._JSONB`` declares, spelled out here so the
#: revision stays a self-contained snapshot rather than importing live models.
_JSONB = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")

revision: str = "b603eb4c27bc"
down_revision: str | None = "b7df22b81517"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manifest_version",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.VARCHAR(length=128), nullable=False),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    with op.batch_alter_table("manifest_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_manifest_version_current",
            ["is_current"],
            unique=True,
            postgresql_where=sa.text("is_current"),
            sqlite_where=sa.text("is_current"),
        )

    op.create_table(
        "manifest_activity",
        sa.Column("activity_type_hash", sa.BigInteger(), nullable=True),
        sa.Column(
            "mode_types",
            _JSONB,
            nullable=False,
        ),
        sa.Column("direct_mode_type", sa.Integer(), nullable=True),
        sa.Column("max_party", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    op.create_table(
        "manifest_activity_type",
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    op.create_table(
        "manifest_collectible",
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("item_hash", sa.BigInteger(), nullable=True),
        sa.Column(
            "parent_node_hashes",
            _JSONB,
            nullable=False,
        ),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    op.create_table(
        "manifest_destination",
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    op.create_table(
        "manifest_equipment_slot",
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    op.create_table(
        "manifest_item",
        sa.Column("name_lower", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("item_type", sa.Integer(), nullable=False),
        sa.Column("item_type_display_name", sa.Text(), nullable=False),
        sa.Column("tier_type_name", sa.Text(), nullable=False),
        sa.Column("class_type", sa.Integer(), nullable=False),
        sa.Column("bucket_type_hash", sa.BigInteger(), nullable=True),
        sa.Column("collectible_hash", sa.BigInteger(), nullable=True),
        sa.Column("season_number", sa.Integer(), nullable=True),
        sa.Column(
            "trait_ids",
            _JSONB,
            nullable=False,
        ),
        sa.Column("redacted", sa.Boolean(), nullable=False),
        sa.Column(
            "raw",
            _JSONB,
            nullable=True,
        ),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    with op.batch_alter_table("manifest_item", schema=None) as batch_op:
        batch_op.create_index(
            "ix_manifest_item_name", ["version_id", "name_lower"], unique=False
        )
        batch_op.create_index(
            "ix_manifest_item_type", ["version_id", "item_type"], unique=False
        )

    op.create_table(
        "manifest_perk",
        sa.Column("icon", sa.Text(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    op.create_table(
        "manifest_presentation_node",
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    op.create_table(
        "manifest_stat",
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    op.create_table(
        "manifest_vendor",
        sa.Column("vendor_identifier", sa.Text(), nullable=False),
        sa.Column(
            "locations",
            _JSONB,
            nullable=False,
        ),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["manifest_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("version_id", "hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manifest_vendor")
    op.drop_table("manifest_stat")
    op.drop_table("manifest_presentation_node")
    op.drop_table("manifest_perk")
    with op.batch_alter_table("manifest_item", schema=None) as batch_op:
        batch_op.drop_index("ix_manifest_item_type")
        batch_op.drop_index("ix_manifest_item_name")

    op.drop_table("manifest_item")
    op.drop_table("manifest_equipment_slot")
    op.drop_table("manifest_destination")
    op.drop_table("manifest_collectible")
    op.drop_table("manifest_activity_type")
    op.drop_table("manifest_activity")
    with op.batch_alter_table("manifest_version", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_manifest_version_current",
            postgresql_where=sa.text("is_current"),
            sqlite_where=sa.text("is_current"),
        )

    op.drop_table("manifest_version")
    # ### end Alembic commands ###
